setup and  mobile version skeleton
milen-ale/my--portfolio pull request #1
Opened 2022-05-31 21:24 UTC by milen-ale

I have added index.html and  style.css, and file for my mobile version skeleton page. and
In order to layout the elements on the page i used Flexbox

2022-05-31 21:28 UTC, Ginohmk requested changes
Hi @milen-ale , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors, please make sure all linters pass before requesting for a review. 

Reviewer slack `@kanu mike chibundu`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-01 11:42 UTC, sja-thedude requested changes
## Invalid Code Review Request ❌

Hi @milen-ale, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that has linter errors, kindly fix it. All linters should have green checkmarks.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-06-01 19:38 UTC, milen-ale commented
I have fixed all linter errors based on the reviews I got from the code reviewers, I have included index.html, style.css, and images used to build the portfolio.

2022-06-01 20:01 UTC, zieeco requested changes
Hi @milen-ale 

<img src="https://media0.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Nice design :heavy_check_mark: 
- Linters are passing :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 20:01 UTC, zieeco commented on index.html
> +      </h2>
**[REQUIRED CHANGES]**

- [ ] Please, kindly use an h1 tag instead of an h2 as the h1 is the main heading on your page. This helps to improve web accessibility.

2022-06-01 20:01 UTC, zieeco commented on README.md
> +
**[REQUIRED CHANGES]**


- Please, kindly remove this header as you're not making use of it.

2022-06-01 20:01 UTC, zieeco commented on README.md
> +The first step is to create a github repository, after that clone the repository. After cloning the repository add readme, .gitignore and linter-config files. Next, add HTML and CSS files to check if
**[REQUIRED CHANGES]**

- Please, kindly update the getting started by telling the user how to clone and run your project locally in their machie

2022-06-02 08:35 UTC, ishimwezachee approved these changes
Hi @milen-ale , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

## Optional suggestions

- [OPTIONAL] I recommend you to resolve the conflict that you have from this branch so that you can be able to merge to the main branch.  

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 12:00 UTC, merged